#Create App Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ticketing
  namespace: egs3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-ticketing
  template:
    metadata:
      labels:
        app: app-ticketing
    spec:
      containers:
      - name: app-ticketing
        image: registry.deti:5000/ticketing/app-ticketing:202206221407
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: postgres-ticketing-config
        volumeMounts:
          - name: ticketing-secret
            mountPath: "/tmp/secrets"
            readOnly: true
      volumes:
        - name: ticketing-secret
          secret:
            secretName: ticketing-secret
      restartPolicy: Always

#Create Service
---
apiVersion: v1
kind: Service
metadata:
  name: app-ticketing
  namespace: egs3
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app-ticketing